# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/config.py
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 8
MODEL:
  ARCHITECTURE: 'sam_vit_b'
  INPUT_SIZE: [1, 1024, 1024]
  OUTPUT_SIZE: [1, 1024, 1024]
  IN_PLANES: 1
  OUT_PLANES: 3
  LOSS_OPTION: [["WeightedCE"]]
  LOSS_WEIGHT: [[1.0]]
  # Currently for multi-class semantic segmentation, only one
  # target option is supported. Using other options with semantic
  # segmentation will be supported in future release.
  TARGET_OPT: ["9-3"]
  WEIGHT_OPT: [["1"]]
  OUTPUT_ACT: [["none"]]
  FILTERS: [32, 64, 128, 256, 512]
AUGMENTOR:
    MISSINGPARTS:
        ENABLED: FALSE
DATASET:
  IMAGE_NAME: 'Sec_0002_part1.png@Shank3b_rb706_S1_export_s0_export_partaera_s0.tif'
  LABEL_NAME: 'shank3b_part1_label_correction.vsseg_export_s0.tif@Shank3b_rb706_S1_export_partaera_correction_remove(To_train).tif'
  INPUT_PATH: '/ygs/personal/zhujing/RB706_1'
  OUTPUT_PATH: 'outputs/train_1'
  PAD_SIZE: [0, 256, 256]
  DATA_SCALE: [1.0, 1.0, 1.0]
  REJECT_SAMPLING:
    SIZE_THRES: 1000
    P: 1.0
  DISTRIBUTED: False
  DO_2D: True
  LOAD_2D: True
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.01
  ITERATION_STEP: 1
  ITERATION_SAVE: 10000
  ITERATION_TOTAL: 200000
  SAMPLES_PER_BATCH: 2
#  STEPS: (40000, 45000)
INFERENCE:
  INPUT_SIZE: [1, 1024, 1024]
  OUTPUT_SIZE: [1, 1024, 1024]
  IMAGE_NAME: "Shank3b_model2_Training_rawEMimage_s0.tif"
  OUTPUT_PATH: "/ygs/personal/zhujing/RB706_1/seg_outputs"
  AUG_MODE: mean
  AUG_NUM: None
  OUTPUT_NAME: Shank3b_model2_Training_rawEMimage_based_trainfive
  STRIDE: [1, 256, 256]
  SAMPLES_PER_BATCH: 2
  PAD_SIZE: [0, 512, 512]
  OUTPUT_ACT: ["softmax"]
