SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 8
  PARALLEL: DP
MODEL:
  ARCHITECTURE: unetr
  INPUT_SIZE: [16, 256, 256] #Must be divisible by patch size (16, 16, 16)
  OUTPUT_SIZE: [16, 256, 256]
  LABEL_DILATION: None
  UNETR_FEATURE_SIZE: 16
  HIDDEN_SIZE: 768
  MLP_DIM: 3072
  UNETR_NUM_HEADS: 12
  POS_EMBED: 'perceptron'
  NORM_NAME: 'instance'
  CONV_BLOCK: False
  RES_BLOCK: True
  UNETR_DROPOUT_RATE: 0.0
DATASET:
  IMAGE_NAME: train.h5
  LABEL_NAME: train-labels.h5
  INPUT_PATH: ./data # or your own dataset path
  OUTPUT_PATH: ./outputs/transformer
  IMAGE_SCALE: [1.0, 1.0, 1.0]
  VALID_MASK_SCALE: [1.0, 1.0, 1.0]
  PAD_MODE: 'reflect'
SOLVER:
  NAME: SGD
  ITERATION_VAL: 4000
INFERENCE:
  INPUT_PATH: ./data
  IMAGE_NAME: test.h5 # or path to your test images
  OUTPUT_PATH: ./outputs/transformer/test
  PAD_SIZE: [4, 64, 64]
  STRIDE: [4, 128, 128]
  SAMPLES_PER_BATCH: 2
